### PR TITLE
Fix build pipeline issues

### PR DESCRIPTION
**Pull request by pixeldesu**
Tests started failing on main after #2042 was merged, while they work just fine locally (and the functionality in itself works fine too)

Let's see if explicitly including `TextHelper` fixes it.

### CODE REVIEW

**Comment by pixeldesu** [comment]
@nilsding help!

Okay, adjusting the include just shows a different method missing, now we're at

```
undefined method `full_sanitizer' for TimelineController:Class
```

Even worse, here even UseCase::Report stuff fails now? It says `where` is not defined on `Report`. What the hell?

Something is seriously broken and I have no idea what, to be honest. Maybe some wrongly installed version? But clearing Action caches (at least the ones that I _think_ matter) didn't change anything either.
